FROM ubuntu:focal
#EXPOSE 6800
ADD ./sources.list /etc/apt/ 
ADD aria2.conf /etc/aria2/aria2.conf

RUN touch /etc/aria2/aria2.session
RUN chmod -R 755 /etc/aria2
RUN mkdir /data
RUN apt update && apt upgrade -y
RUN apt update && apt install aria2 -y

ENTRYPOINT aria2c --conf-path=/etc/aria2/aria2.conf 




